[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.39/platform-espressif32.zip
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
build_type = debug

lib_deps =
    https://github.com/robotdyn-dimmer/rbdimmerESP32.git